export const SKILL_CATEGORIES = [
  {
    id: 'education',
    name: 'Éducation',
    skills: [
      'Mathématiques',
      'Physique',
      'Chimie',
      'SVT',
      'Français',
      'Anglais',
      'Arabe',
      'Philosophie',
      'Histoire-Géo',
      'Économie',
    ],
  },
  {
    id: 'technology',
    name: 'Technologie',
    skills: [
      'Programmation',
      'Développement Web',
      'Développement Mobile',
      'Data Science',
      'Design UI/UX',
      'Marketing Digital',
      'Réseaux',
      'Cybersécurité',
    ],
  },
  {
    id: 'languages',
    name: 'Langues',
    skills: [
      'Français',
      'Anglais',
      'Arabe',
      'Espagnol',
      'Allemand',
      'Italien',
      'Chinois',
      'Japonais',
    ],
  },
  {
    id: 'arts',
    name: 'Arts & Créativité',
    skills: [
      'Dessin',
      'Peinture',
      'Musique',
      'Chant',
      'Danse',
      'Photographie',
      'Vidéo',
      'Théâtre',
    ],
  },
  {
    id: 'sports',
    name: 'Sport & Bien-être',
    skills: [
      'Fitness',
      'Yoga',
      'Nutrition',
      'Football',
      'Basketball',
      'Tennis',
      'Natation',
      'Arts Martiaux',
    ],
  },
  {
    id: 'business',
    name: 'Business & Finance',
    skills: [
      'Comptabilité',
      'Gestion',
      'Entrepreneuriat',
      'Marketing',
      'Finance',
      'Investissement',
      'Trading',
      'E-commerce',
    ],
  },
  {
    id: 'crafts',
    name: 'Artisanat & Services',
    skills: [
      'Plomberie',
      'Électricité',
      'Menuiserie',
      'Peinture',
      'Jardinage',
      'Nettoyage',
      'Couture',
      'Cuisine',
    ],
  },
];

export const EXPERIENCE_LEVELS = [
  {
    id: 'student',
    title: 'Étudiant',
    description: 'Je suis actuellement étudiant',
    icon: 'school-outline',
    requiresYear: true,
  },
  {
    id: 'engineering_student',
    title: 'Élève ingénieur',
    description: 'Je suis en école d\'ingénieur',
    icon: 'construct-outline',
    requiresYear: true,
  },
  {
    id: 'junior_engineer',
    title: 'Jeune ingénieur',
    description: 'J\'ai moins de 3 ans d\'expérience',
    icon: 'briefcase-outline',
    requiresYear: false,
  },
  {
    id: 'teacher',
    title: 'Enseignant',
    description: 'Je suis enseignant professionnel',
    icon: 'person-outline',
    requiresYear: false,
  },
  {
    id: 'freelance',
    title: 'Freelance',
    description: 'Je travaille en indépendant',
    icon: 'laptop-outline',
    requiresYear: false,
  },
  {
    id: 'expert',
    title: 'Expert',
    description: 'J\'ai plus de 5 ans d\'expérience',
    icon: 'trophy-outline',
    requiresYear: false,
  },
];

export const STUDENT_YEARS = [
  '1ère année',
  '2ème année',
  '3ème année',
  '4ème année',
  '5ème année',
  'Master 1',
  'Master 2',
  'Doctorat',
];

export const PRICING_TIERS = [
  {
    id: 'basic',
    title: 'Basique',
    range: '50-100 MAD',
    min: 50,
    max: 100,
    description: 'Idéal pour débuter',
    color: '#4CAF50',
  },
  {
    id: 'standard',
    title: 'Standard',
    range: '100-200 MAD',
    min: 100,
    max: 200,
    description: 'Prix moyen du marché',
    color: '#2196F3',
    recommended: true,
  },
  {
    id: 'premium',
    title: 'Premium',
    range: '200-500 MAD',
    min: 200,
    max: 500,
    description: 'Pour experts confirmés',
    color: '#9C27B0',
  },
  {
    id: 'custom',
    title: 'Personnalisé',
    range: 'À définir',
    description: 'Fixez votre propre tarif',
    color: '#FF9800',
  },
];

export const BIO_TEMPLATES = [
  {
    category: 'student',
    template: 'Étudiant(e) en {year}, passionné(e) par {skills}. Je souhaite partager mes connaissances et aider d\'autres étudiants à réussir.',
  },
  {
    category: 'engineering_student',
    template: 'Élève ingénieur en {year}, spécialisé(e) en {skills}. J\'accompagne les étudiants dans leur parcours académique avec des méthodes efficaces.',
  },
  {
    category: 'teacher',
    template: 'Enseignant(e) professionnel(le) avec plusieurs années d\'expérience en {skills}. Je propose des cours adaptés à tous les niveaux.',
  },
  {
    category: 'freelance',
    template: 'Freelance spécialisé(e) en {skills}. Je partage mon expérience pratique pour vous aider à maîtriser ces compétences.',
  },
  {
    category: 'expert',
    template: 'Expert(e) en {skills} avec plus de 5 ans d\'expérience. Je propose un accompagnement personnalisé pour atteindre vos objectifs.',
  },
];

export const MOROCCAN_CITIES = [
  'Casablanca',
  'Rabat',
  'Marrakech',
  'Fès',
  'Tanger',
  'Agadir',
  'Meknès',
  'Oujda',
  'Kenitra',
  'Tétouan',
  'Safi',
  'Mohammedia',
  'Khouribga',
  'El Jadida',
  'Béni Mellal',
  'Nador',
  'Taza',
  'Settat',
  'Ksar El Kebir',
  'Laâyoune',
];
